version: '3.1'

services:
  web_frontend:
    build:
      context: ./web_frontend
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_HH_API_URL=localhost:3000
    ports:
      - 3001:3001
    volumes:
      - ./web_frontend:/app

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./api:/app
    environment:
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DB_USER=${RDS_DB_USER}
      - RDS_DB_PW=${RDS_DB_PW}
      - RDS_DB_HOST=hackr-harvest-rds.ch5p5impb82f.us-west-2.rds.amazonaws.com
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AMZN_SDK_ACCESS_KEY=${AMZN_SDK_ACCESS_KEY}
      - AMZN_SDK_SECRET_ACCESS_KEY=${AMZN_SDK_SECRET_ACCESS_KEY}
      - COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - JWT_SECRET=${JWT_SECRET}
