FROM node:20.8-bookworm

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
COPY index.js /app/
COPY migrations /app/
COPY models /app/
COPY config /app/
COPY dbConnection.js /app/
COPY .sequelizerc /app/

RUN npm ci

CMD npm run start
